default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: qweeky

test:
  <<: *default
  database: qweeky_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
